name = "MKK Scenario Game Tools"
prefix = "sgt"
mainprefix = "x"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
exclude = ["*.md", "*c4d", "*.xcf", "*.pptx"]
include = ["./include", "mod.paa"]

[hemtt.build]
optional_mod_folders = false # Default: true

[hemtt.release]
sign = false    # Default: true
archive = false # Default: true
